# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{metrify}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stephen Abrams"]
  s.date = %q{2010-12-05}
  s.description = %q{Framework to aggregate and display data over time. Assumes highcharts installation.}
  s.email = %q{abrams.stephen@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "app/controllers/metrify/metrify_controller.rb",
     "app/helpers/metrify/metrify_helper.rb",
     "app/views/metrify/_chart.html.erb",
     "app/views/metrify/_graph.html.erb",
     "app/views/metrify/_mailer_charts_summary.html.erb",
     "app/views/metrify/_mailer_single_chart.html.erb",
     "app/views/metrify/_time_links.erb",
     "lib/metrify.rb",
     "spec/database.yml",
     "spec/debug.log",
     "spec/metrify.yml",
     "spec/metrify_spec.rb",
     "spec/schema.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/sabrams/metrify}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Framework to aggregate and display data over time}
  s.test_files = [
    "spec/metrify_spec.rb",
     "spec/schema.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0"])
  end
end

